manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: VynDragon
      url-base: https://github.com/VynDragon

  projects:
    - name: zephyr
      remote: VynDragon
      revision: bflb/work_bflb
      import:
        name-allowlist:
          - hal_bouffalolab
