#include "building.h"

#include "cat2.h"

#include "cube.h"

#include "plane.h"

#include "sphere.h"

#include "wood.h"

static const Engine_Object demo_scene[];

static const E_Collider demo_scene_colliders[][1] = {
	{
		{
		.axisplane.size.y = 1,
		.axisplane.bouncyness = 0xFF,
		.axisplane.size.x = 1*L3_F,
		.axisplane.size.z = 1*L3_F,
		.type = ENGINE_COLLIDER_APLANEY,
		},
	},
	{
		{
		.cube.size.y = 2.5*L3_F,
		.cube.bouncyness = 128,
		.cube.size.x = 2.5*L3_F,
		.cube.size.z = 4.5*L3_F,
		.type = ENGINE_COLLIDER_CUBE,
		},
	},
	{
		{
		.cube.size.y = 2.5*L3_F,
		.cube.bouncyness = 128,
		.cube.size.x = 2.5*L3_F,
		.cube.size.z = 4.5*L3_F,
		.type = ENGINE_COLLIDER_CUBE,
		},
	},
	{
		{
		.cube.size.y = 2.5*L3_F,
		.cube.bouncyness = 128,
		.cube.size.x = 2.5*L3_F,
		.cube.size.z = 4.5*L3_F,
		.type = ENGINE_COLLIDER_CUBE,
		},
	},
	{
		{
		.cube.size.y = 0.5*L3_F,
		.cube.bouncyness = 128,
		.cube.size.x = 0.5*L3_F,
		.cube.size.z = 0.5*L3_F,
		.type = ENGINE_COLLIDER_CUBE,
		},
	},
	{
		{
		.sphere.bouncyness = 128,
		.sphere.size = 2*L3_F,
		.type = ENGINE_COLLIDER_SPHERE,
		},
	},
	{
		{
		.axisplane.size.y = 1,
		.axisplane.bouncyness = 0xFF,
		.axisplane.size.x = 1*L3_F,
		.axisplane.size.z = 1*L3_F,
		.type = ENGINE_COLLIDER_APLANEY,
		},
	},
};

static const Engine_Collisions demo_scene_collisions[] = {
	{
		.colliders = demo_scene_colliders[0],
		.colliderCount = 1,
	},
	{
		.colliders = demo_scene_colliders[1],
		.colliderCount = 1,
	},
	{
		.colliders = demo_scene_colliders[2],
		.colliderCount = 1,
	},
	{
		.colliders = demo_scene_colliders[3],
		.colliderCount = 1,
	},
	{
		.colliders = demo_scene_colliders[4],
		.colliderCount = 1,
	},
	{
		.colliders = demo_scene_colliders[5],
		.colliderCount = 1,
	},
	{
		.colliders = demo_scene_colliders[6],
		.colliderCount = 1,
	},
};

static const Engine_Object demo_scene[] = {
	{
		.visual.model = &plane_model,
		.visual.config.backfaceCulling = 1,
		.visual.config.visible = L3_VISIBLE_WIREFRAME,
		.visual.transform.scale.x = L3_F*1000,
		.visual.transform.scale.y = L3_F,
		.visual.transform.scale.z = L3_F*1000,
		.visual.transform.scale.w = 0,
		.visual.transform.translation.x = 0,
		.visual.transform.translation.y = 0,
		.visual.transform.translation.z = 0,
		.visual.transform.translation.w = L3_F,
		.visual.transform.rotation.x = 0,
		.visual.transform.rotation.y = 0,
		.visual.transform.rotation.z = 0,
		.visual.transform.rotation.w = L3_F,
		.view_range = 8192 * L3_F,
		.visual_type = ENGINE_VISUAL_NOTHING,
		.process = 0,
		.data = 0,
		.collisions = &(demo_scene_collisions[0]),
	},
	{
		.visual.model = &building_01_model,
		.visual.config.backfaceCulling = 1,
		.visual.config.visible = L3_VISIBLE_TEXTURED,
		.visual.transform.scale.x = L3_F,
		.visual.transform.scale.y = L3_F,
		.visual.transform.scale.z = L3_F,
		.visual.transform.scale.w = 0,
		.visual.transform.translation.x = 0,
		.visual.transform.translation.y = 180,
		.visual.transform.translation.z = 10*L3_F,
		.visual.transform.translation.w = L3_F,
		.visual.transform.rotation.x = 0,
		.visual.transform.rotation.y = 0,
		.visual.transform.rotation.z = 0,
		.visual.transform.rotation.w = L3_F,
		.view_range = 8192 * L3_F,
		.visual_type = ENGINE_VISUAL_MODEL,
		.process = 0,
		.data = 0,
		.collisions = &(demo_scene_collisions[1]),
	},
	{
		.visual.model = &building_01_model,
		.visual.config.backfaceCulling = 1,
		.visual.config.visible = L3_VISIBLE_WIREFRAME,
		.visual.transform.scale.x = L3_F,
		.visual.transform.scale.y = L3_F,
		.visual.transform.scale.z = L3_F,
		.visual.transform.scale.w = 0,
		.visual.transform.translation.x = -10*L3_F,
		.visual.transform.translation.y = 180,
		.visual.transform.translation.z = 10*L3_F,
		.visual.transform.translation.w = L3_F,
		.visual.transform.rotation.x = 0,
		.visual.transform.rotation.y = 0,
		.visual.transform.rotation.z = 0,
		.visual.transform.rotation.w = L3_F,
		.view_range = 8192 * L3_F,
		.visual_type = ENGINE_VISUAL_MODEL,
		.process = 0,
		.data = 0,
		.collisions = &(demo_scene_collisions[2]),
	},
	{
		.visual.model = &building_01_model,
		.visual.config.backfaceCulling = 1,
		.visual.config.visible = L3_VISIBLE_SOLID,
		.visual.transform.scale.x = L3_F,
		.visual.transform.scale.y = L3_F,
		.visual.transform.scale.z = L3_F,
		.visual.transform.scale.w = 0,
		.visual.transform.translation.x = 10*L3_F,
		.visual.transform.translation.y = 180,
		.visual.transform.translation.z = 10*L3_F,
		.visual.transform.translation.w = L3_F,
		.visual.transform.rotation.x = 0,
		.visual.transform.rotation.y = 0,
		.visual.transform.rotation.z = 0,
		.visual.transform.rotation.w = L3_F,
		.view_range = 8192 * L3_F,
		.visual_type = ENGINE_VISUAL_MODEL,
		.process = 0,
		.data = 0,
		.collisions = &(demo_scene_collisions[3]),
	},
	{
		.visual.model = &cube_model,
		.visual.config.backfaceCulling = 1,
		.visual.config.visible = L3_VISIBLE_SOLID | L3_VISIBLE_WIREFRAME | L3_VISIBLE_DISTANCELIGHT,
		.visual.transform.scale.x = L3_F,
		.visual.transform.scale.y = L3_F,
		.visual.transform.scale.z = L3_F,
		.visual.transform.scale.w = 0,
		.visual.transform.translation.x = 2*L3_F,
		.visual.transform.translation.y = L3_F,
		.visual.transform.translation.z = 2*L3_F,
		.visual.transform.translation.w = L3_F,
		.visual.transform.rotation.x = 0,
		.visual.transform.rotation.y = 0,
		.visual.transform.rotation.z = 0,
		.visual.transform.rotation.w = L3_F,
		.view_range = 8192 * L3_F,
		.visual_type = ENGINE_VISUAL_MODEL,
		.process = 0,
		.data = 0,
		.collisions = &(demo_scene_collisions[4]),
	},
	{
		.visual.model = &sphere_model,
		.visual.config.backfaceCulling = 1,
		.visual.config.visible = L3_VISIBLE_WIREFRAME,
		.visual.transform.scale.x = 2*L3_F,
		.visual.transform.scale.y = 2*L3_F,
		.visual.transform.scale.z = 2*L3_F,
		.visual.transform.scale.w = 0,
		.visual.transform.translation.x = 4*L3_F,
		.visual.transform.translation.y = 0,
		.visual.transform.translation.z = 2*L3_F,
		.visual.transform.translation.w = L3_F,
		.visual.transform.rotation.x = 0,
		.visual.transform.rotation.y = 0,
		.visual.transform.rotation.z = 0,
		.visual.transform.rotation.w = L3_F,
		.view_range = 8192 * L3_F,
		.visual_type = ENGINE_VISUAL_MODEL,
		.process = 0,
		.data = 0,
		.collisions = &(demo_scene_collisions[5]),
	},
	{
		.visual.model = &plane_model,
		.visual.config.backfaceCulling = 0,
		.visual.config.visible = L3_VISIBLE_WIREFRAME,
		.visual.transform.scale.x = L3_F*2,
		.visual.transform.scale.y = L3_F,
		.visual.transform.scale.z = L3_F*2,
		.visual.transform.scale.w = 0,
		.visual.transform.translation.x = -4*L3_F,
		.visual.transform.translation.y = 2*L3_F,
		.visual.transform.translation.z = 2*L3_F,
		.visual.transform.translation.w = L3_F,
		.visual.transform.rotation.x = 0,
		.visual.transform.rotation.y = 0,
		.visual.transform.rotation.z = 0,
		.visual.transform.rotation.w = L3_F,
		.view_range = 8192 * L3_F,
		.visual_type = ENGINE_VISUAL_MODEL,
		.process = 0,
		.data = 0,
		.collisions = &(demo_scene_collisions[6]),
	},
	{
		.visual.billboard = &cat2_billboard,
		.visual.config.backfaceCulling = 1,
		.visual.config.visible = L3_VISIBLE_BILLBOARD,
		.visual.transform.scale.x = L3_F * 1,
		.visual.transform.scale.y = L3_F * 1,
		.visual.transform.scale.z = L3_F * 1,
		.visual.transform.scale.w = 0,
		.visual.transform.translation.x = 0*L3_F,
		.visual.transform.translation.y = 256,
		.visual.transform.translation.z = 5*L3_F,
		.visual.transform.translation.w = L3_F,
		.visual.transform.rotation.x = 0,
		.visual.transform.rotation.y = 0,
		.visual.transform.rotation.z = 0,
		.visual.transform.rotation.w = L3_F,
		.view_range = 192 * L3_F,
		.visual_type = ENGINE_VISUAL_BILLBOARD,
		.process = 0,
		.data = 0,
		.collisions = 0,
	},
	{
		.visual.model = &wood_model,
		.visual.config.backfaceCulling = 0,
		.visual.config.visible = L3_VISIBLE_SOLID,
		.visual.transform.scale.x = L3_F * 0.25,
		.visual.transform.scale.y = L3_F * 0.25,
		.visual.transform.scale.z = L3_F * 0.25,
		.visual.transform.scale.w = 0,
		.visual.transform.translation.x = 0,
		.visual.transform.translation.y = 0,
		.visual.transform.translation.z = 0,
		.visual.transform.translation.w = L3_F,
		.visual.transform.rotation.x = 0,
		.visual.transform.rotation.y = 0,
		.visual.transform.rotation.z = 0,
		.visual.transform.rotation.w = L3_F,
		.view_range = 8192 * L3_F,
		.visual_type = ENGINE_VISUAL_MODEL,
		.process = 0,
		.data = 0,
	},
};
